name: Update PR Status

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'dev'

jobs:
  update_pr_status:
    runs-on: ubuntu-latest

    steps:
      - name: Printing the current context
        uses: actions/github-script@v6
        with:
          script: |
            console.log("context")
            console.log(context)

      - name: Determine if push is to dev branch
        id: is_dev_branch
        run: echo "::set-output name=is_dev::${{ startsWith(github.ref, 'refs/heads/dev') }}"



      - name: Determine if equal to an open pr last commit
        if: ${{steps.is_dev_branch.outputs.is_dev == 'true'}}
        uses: actions/github-script@v6
        with:
          script: |
            const devCommit = context.payload.after;
            console.log("devCommit")
            console.log(devCommit)
            const openPRs = await github.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            console.log("openPRs")
            console.log(openPRs)
            const match = openPRs.data.some(pr => pr.head.sha === devCommit);
            console.log(match)


      - name: Determine if all the commits in the pr exist in dev
        if: ${{steps.is_dev_branch.outputs.is_dev != 'true'}}
        run: echo "is not dev"

    