name: Update PR Status

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'dev'

jobs:
  update_pr_status:
    runs-on: ubuntu-latest

    steps:
      - name: Printing the current context
        uses: actions/github-script@v6
        with:
          script: |
            console.log("context")
            console.log(context)


      - name: Get PR number if any
        id: check_commit
        uses: actions/github-script@v6
        with:
          script: |
            const issueNumber = context.issue.number
            const ref = context.payload.after;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            console.log(issueNumber)
            console.log(ref)
            console.log(owner)
            console.log(repo)

            
            const { data: pullRequest } = await github.rest.repos.getCommit({owner, repo, ref});
  
            const prNumber = pullRequest.pull_request ? pullRequest.pull_request.number : null;
  
            console.log(`::set-output name=pr_number::${prNumber}`);
          
      - name: Output pr number
        run: echo "PR number? ${{ steps.check_commit.outputs.pr_number }}"

    