name: Update PR Status

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'dev'

jobs:
  update_pr_status:
    runs-on: ubuntu-latest

    steps:
      - name: Printing the current context
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context)

      - name: Determine if push is to dev branch
        id: is_dev_branch
        run: echo "::set-output name=is_dev::${{ startsWith(github.ref, 'refs/heads/dev') }}"



      - name: Determine if any pr open with this commit
        if: ${{steps.is_dev_branch.outputs.is_dev == 'true'}}
        uses: actions/github-script@v6
        with:
          script: |
            const commit_sha = context.payload.after;
            const owner = context.repo.owner
            const repo = context.repo.repo
            const {data} = await github.rest.repos.listPullRequestsAssociatedWithCommit({ commit_sha, owner, repo })
            if(data.length == 0){
              console.log("no PR to tag")
              return
            }
            console.log(data)

            github.rest.issues.addLabels({
              issue_number: prNumber,
              owner,
              repo,
              labels: ['merged'],
            });
            github.rest.issues.removeLabel({
              issue_number: prNumber,
              owner,
              repo,
              name: 'not merged',
            });




      - name: Determine if latest pr commit exists in dev branch
        if: ${{steps.is_dev_branch.outputs.is_dev != 'true'}}
        uses: actions/github-script@v6
        with:
          script: |
            const prCommit = context.payload.after;
            const prNumber = context.payload.pull_request.number
            const owner = context.repo.owner
            const repo = context.repo.repo

            const devCommits = await github.rest.repos.listCommits({ owner, repo, sha: 'dev' });

            const commitExistsInDev = devCommits.data.some(commit => commit.sha === prCommit);
            if(commitExistsInDev){
              github.rest.issues.addLabels({
                issue_number: prNumber,
                owner,
                repo,
                labels: ['merged'],
              });
              github.rest.issues.removeLabel({
                issue_number: prNumber,
                owner,
                repo,
                name: 'not merged',
              });
            }else{
              github.rest.issues.addLabels({
                issue_number: prNumber,
                owner,
                repo,
                labels: ['not merged'],
              });
              github.rest.issues.removeLabel({
                issue_number: prNumber,
                owner,
                repo,
                name: 'merged',
              });            
            }

          

    