name: Update PR Status

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - 'dev'

jobs:
  update_pr_status:
    runs-on: ubuntu-latest

    steps:
      - name: Printing the current context
        uses: actions/github-script@v6
        with:
          script: |
            console.log("context")
            console.log(context)

      - name: Determine if push is to dev branch
        id: is_dev_branch
        run: echo "::set-output name=is_dev::${{ startsWith(github.ref, 'refs/heads/dev') }}"



      - name: Determine if equal to an open pr last commit
        uses: actions/github-script@v6
        with:
          script: |
            const devCommit = context.payload.after;
            const commitSha = context.sha
            console.log("devCommit")
            console.log(devCommit)
            console.log("commitSha")
            console.log(commitSha)
            const {data} = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              commit_sha: context.sha,
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            console.log(data)



      - name: Determine if all the commits in the pr exist in dev
        if: ${{steps.is_dev_branch.outputs.is_dev != 'true'}}
        run: echo "is not dev"

    